### ISSUE TITLE
texas.lbr TPS62177 Pin assignment error 

### ISSUE THREAD

**Issue by CRprog** [robertstarr/lbr_user#39]
Hi !
Just as a hint:
In your texas.lbr for the TPS62177 the pins 1 and 7 are swapped. (PG und PGND)
Btw: Thanks for your helpful collection. 

Regards.

**Comment by robertstarr** [comment]
On 10/5/2021 4:49 PM, CRprog wrote:
    
    
      
      Hi !
        Just as a hint:
        In your texas.lbr for the TPS62177 the pins 1 and 7 are swapped.
        (PG und PGND)
        Btw: Thanks for your helpful collection.
      Regards.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/robertstarr/lbr_user/issues/39",
"url": "https://github.com/robertstarr/lbr_user/issues/39",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    Sorry, I corrected the
        swapped pins.
    Bob
